services:
  - type: web
    name: music-web-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: music-data
      mountPath: /data
      sizeGB: 1