services:
  - type: web
<<<<<<< HEAD
    name: music-player
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 10000
=======
    name: music-web-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: music-data
      mountPath: /data
      sizeGB: 1
>>>>>>> bf240b4 (app.js)
